//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.01 at 08:56:19 PM CEST 
//


package com.example.xml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for doctor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="doctor">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.health_care.com/user}user">
 *       &lt;sequence>
 *         &lt;element name="specialty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="patient_id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "doctor", propOrder = {
    "specialty",
    "patientId",
    "appointmentIds"
})
@XmlRootElement(name = "doctor")
public class Doctor
    extends User
{

    @XmlElement(required = true)
    protected String specialty;
    @XmlElement(name = "patient_id")
    protected List<String> patientId;
    @XmlElement(name = "appointment_ids")
    protected List<String> appointmentIds;

    /**
     * Gets the value of the specialty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * Sets the value of the specialty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialty(String value) {
        this.specialty = value;
    }

    /**
     * Gets the value of the patientId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patientId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatientId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPatientId() {
        if (patientId == null) {
            patientId = new ArrayList<String>();
        }
        return this.patientId;
    }
    
    public List<String> getAppointmentIds() {
        if (appointmentIds == null) {
        	appointmentIds = new ArrayList<String>();
        }
        return this.appointmentIds;
    }
    
    public void setAppointmentIds(List<String> value) {
    	
        this.appointmentIds = value;
    }

}
