//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.01 at 08:56:19 PM CEST 
//


package com.example.xml.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.xml.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Doctor_QNAME = new QName("http://www.health_care.com/doctor", "doctor");
    private final static QName _User_QNAME = new QName("http://www.health_care.com/user", "user");
    private final static QName _Patient_QNAME = new QName("http://www.health_care.com/patient", "patient");
    private final static QName _Record_QNAME = new QName("http://www.health_care.com/record", "record");
    private final static QName _Appointment_QNAME = new QName("http://www.health_care.com/appointment", "appointment");


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.xml.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Doctor }
     * 
     */
    public Doctor createDoctor() {
        return new Doctor();
    }

    /**
     * Create an instance of {@link User.Name }
     * 
     */
    public User.Name createUserName() {
        return new User.Name();
    }

    
    public Patient createPatient() {
        return new Patient();
    }
 
    /**
     * Create an instance of {@link Appointment }
     * 
     */
    public Appointment createAppointment() {
        return new Appointment();
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Doctor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.health_care.com/doctor", name = "doctor")
    public JAXBElement<Doctor> createDoctor(Doctor value) {
        return new JAXBElement<Doctor>(_Doctor_QNAME, Doctor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.health_care.com/user", name = "user")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }
    
    @XmlElementDecl(namespace = "http://www.health_care.com/patient", name = "patient")
    public JAXBElement<Patient> createPatient(Patient value) {
        return new JAXBElement<Patient>(_Patient_QNAME, Patient.class, null, value);
    }
    
    @XmlElementDecl(namespace = "http://www.health_care.com/record", name = "record")
    public JAXBElement<Record> createRecord(Record value) {
        return new JAXBElement<Record>(_Record_QNAME, Record.class, null, value);
    }
    
    @XmlElementDecl(namespace = "http://www.health_care.com/appointment", name = "record")
    public JAXBElement<Appointment> createAppointment(Appointment appointment) {
        return new JAXBElement<Appointment>(_Appointment_QNAME, Appointment.class, null, appointment);
    }

}
