//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.07 at 09:28:06 PM CEST 
//


package com.example.xml.model.recordFull;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.example.xml.model.prescription.Prescription;
import com.example.xml.model.referral.Referral;
import com.example.xml.model.report.Report;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.xml.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Report_QNAME = new QName("http://www.health_care.com/report", "report");
    private final static QName _Prescription_QNAME = new QName("http://www.health_care.com/prescription", "prescription");
    private final static QName _Referral_QNAME = new QName("http://www.health_care.com/referral", "referral");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.xml.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RecordFull }
     * 
     */
    public RecordFull createRecordFull() {
        return new RecordFull();
    }

    /**
     * Create an instance of {@link Referral }
     * 
     */
    public Referral createReferral() {
        return new Referral();
    }

    /**
     * Create an instance of {@link Perscription }
     * 
     */
    public Prescription createPerscription() {
        return new Prescription();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Report }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.health_care.com/report", name = "report")
    public JAXBElement<Report> createReport(Report value) {
        return new JAXBElement<Report>(_Report_QNAME, Report.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Perscription }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.health_care.com/prescription", name = "prescription")
    public JAXBElement<Prescription> createPrescription(Prescription value) {
        return new JAXBElement<Prescription>(_Prescription_QNAME, Prescription.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Referral }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.health_care.com/referral", name = "referral")
    public JAXBElement<Referral> createReferral(Referral value) {
        return new JAXBElement<Referral>(_Referral_QNAME, Referral.class, null, value);
    }

}
