//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.07 at 09:01:55 PM CEST 
//


package com.example.xml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="patient_jmbg" type="{http://www.health_care.com/record}jmbg"/>
 *         &lt;element name="patient_name" type="{http://www.health_care.com/record}jmbg"/>
 *         &lt;element name="patient_lastname" type="{http://www.health_care.com/record}jmbg"/>
 *         &lt;element name="patient_lbo" type="{http://www.health_care.com/record}jmbg"/>
 *         &lt;element name="doctor_id" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="doctor_name" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="doctor_lastname" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="reports" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="prescriptions" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="referrals" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patientJmbg",
    "patientName",
    "patientLastname",
    "patientLbo",
    "doctorId",
    "doctorName",
    "doctorLastname",
    "reports",
    "prescriptions",
    "referrals"
})
@XmlRootElement(name = "record")
public class Record {

    @XmlElement(name = "patient_jmbg", required = true)
    protected String patientJmbg;
    @XmlElement(name = "patient_name", required = true)
    protected String patientName;
    @XmlElement(name = "patient_lastname", required = true)
    protected String patientLastname;
    @XmlElement(name = "patient_lbo", required = true)
    protected String patientLbo;
    @XmlElement(name = "doctor_id", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String doctorId;
    @XmlElement(name = "doctor_name", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String doctorName;
    @XmlElement(name = "doctor_lastname", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String doctorLastname;
    protected List<Object> reports;
    protected List<Object> prescriptions;
    protected List<Object> referrals;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anyURI")
    protected String id;

    /**
     * Gets the value of the patientJmbg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientJmbg() {
        return patientJmbg;
    }

    /**
     * Sets the value of the patientJmbg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientJmbg(String value) {
        this.patientJmbg = value;
    }

    /**
     * Gets the value of the patientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * Sets the value of the patientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientName(String value) {
        this.patientName = value;
    }

    /**
     * Gets the value of the patientLastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientLastname() {
        return patientLastname;
    }

    /**
     * Sets the value of the patientLastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientLastname(String value) {
        this.patientLastname = value;
    }

    /**
     * Gets the value of the patientLbo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientLbo() {
        return patientLbo;
    }

    /**
     * Sets the value of the patientLbo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientLbo(String value) {
        this.patientLbo = value;
    }

    /**
     * Gets the value of the doctorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * Sets the value of the doctorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoctorId(String value) {
        this.doctorId = value;
    }

    /**
     * Gets the value of the doctorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * Sets the value of the doctorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoctorName(String value) {
        this.doctorName = value;
    }

    /**
     * Gets the value of the doctorLastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoctorLastname() {
        return doctorLastname;
    }

    /**
     * Sets the value of the doctorLastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoctorLastname(String value) {
        this.doctorLastname = value;
    }

    /**
     * Gets the value of the reports property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reports property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReports().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getReports() {
        if (reports == null) {
            reports = new ArrayList<Object>();
        }
        return this.reports;
    }

    /**
     * Gets the value of the prescriptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prescriptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrescriptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getPrescriptions() {
        if (prescriptions == null) {
            prescriptions = new ArrayList<Object>();
        }
        return this.prescriptions;
    }

    /**
     * Gets the value of the referrals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referrals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferrals().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getReferrals() {
        if (referrals == null) {
            referrals = new ArrayList<Object>();
        }
        return this.referrals;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
