//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.01 at 09:48:32 PM CEST 
//
@javax.xml.bind.annotation.XmlSchema(
        namespace="http://www.health_care.com/record",
        xmlns = {
                @XmlNs(prefix = "record", namespaceURI = "http://www.health_care.com/record"),
                @XmlNs(prefix = "hs", namespaceURI = "http://www.health_care.com/rdf/hs/"),
                @XmlNs(prefix = "", namespaceURI = "http://www.w3.org/ns/rdfa#"),
                @XmlNs(prefix = "xs", namespaceURI = "http://www.w3.org/2001/XMLSchema#")
        },
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package com.example.xml.model.record;


import javax.xml.bind.annotation.XmlNs;